# Generated by Django 6.0.5 on 2026-05-07 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cobros', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cobro',
            name='pagado',
            field=models.BooleanField(default=False),
        ),
    ]
