# Generated by Django 6.0.5 on 2026-05-07 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cobros', '0002_cobro_pagado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cobro',
            name='hora_salida',
            field=models.DateTimeField(blank=True, help_text='Si el auto acaba de ingresar, no rellene hora de salida.', null=True),
        ),
    ]
